name: Pytest ubuntu-latest

on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install socat tmux
        python -m pip install --upgrade pip
        pip install pipenv 
    - name: Run tests
      run: |
        tmux new-session -d -s socat_virtual_ports 'socat -d -d pty,raw,echo=0,crnl  pty,raw,echo=0,crnl'
        pipenv install --dev
        pipenv run pytest test/
        tmux kill-session
